export const photos = [
  {
    src: "/images/about/me_in_beach.jpeg",
    alt: "Felipe Frantz Zanini (ffzanini) - Software Engineer na praia em Pelotas, Brasil",
    width: 732,
    height: 1024,
    className: "rounded",
  },
  {
    src: "/images/about/me_in_rocks.jpeg",
    alt: "Felipe Frantz Zanini - desenvolvedor web e software engineer nas pedras da praia",
    width: 732,
    height: 1024,
    className: "rounded -mt-4",
  },
  {
    src: "/images/about/me_medal.jpeg",
    alt: "Felipe Frantz Zanini (ffzanini) com medalha - desenvolvedor React e Next.js",
    width: 2340,
    height: 3276,
    className: "rounded",
  },
  {
    src: "/images/about/me_sitdown.jpeg",
    alt: "Felipe Frantz Zanini - software engineer e desenvolvedor fullstack sentado",
    width: 732,
    height: 1024,
    className: "rounded -mt-4",
  },
  {
    src: "/images/about/me_claudio_sleeping.jpeg",
    alt: "Felipe Frantz Zanini (ffzanini) com Claudio - desenvolvedor de software",
    width: 2880,
    height: 4032,
    className: "rounded",
  },
  {
    src: "/images/about/me_running.jpeg",
    alt: "Felipe Frantz Zanini correndo - software engineer e desenvolvedor web em Pelotas",
    width: 2662,
    height: 3727,
    className: "rounded",
  },
  {
    src: "/images/about/me_jiujitsu.jpeg",
    alt: "Felipe Frantz Zanini (ffzanini) praticando Jiu Jitsu - desenvolvedor React e faixa marrom",
    width: 2340,
    height: 3276,
    className: "rounded -mt-4",
  },
  {
    src: "/images/about/me_chating.jpeg",
    alt: "Felipe Frantz Zanini conversando - software engineer especializado em desenvolvimento web",
    width: 732,
    height: 1024,
    className: "rounded",
  },
  {
    src: "/images/about/me_claudio_coffee.jpeg",
    alt: "Felipe Frantz Zanini (ffzanini) com Claudio tomando café - desenvolvedor fullstack",
    width: 2206,
    height: 3088,
    className: "rounded -mt-4",
  },
  {
    src: "/images/about/me_playing_piano.jpeg",
    alt: "Felipe Frantz Zanini tocando teclado - software engineer e desenvolvedor de jogos indie",
    width: 732,
    height: 1024,
    className: "rounded",
  },
];
