export const photos = [
  {
    src: "/images/about/me_in_beach.jpeg",
    alt: "Eu na praia",
    width: 732,
    height: 1024,
    className: "rounded",
  },
  {
    src: "/images/about/me_in_rocks.jpeg",
    alt: "Eu na praia nas pedras",
    width: 732,
    height: 1024,
    className: "rounded -mt-4",
  },
  {
    src: "/images/about/me_medal.jpeg",
    alt: "Eu com a medalha",
    width: 2340,
    height: 3276,
    className: "rounded",
  },
  {
    src: "/images/about/me_sitdown.jpeg",
    alt: "Eu sentado em uma pedra",
    width: 732,
    height: 1024,
    className: "rounded -mt-4",
  },
  {
    src: "/images/about/me_claudio_sleeping.jpeg",
    alt: "Eu com Claudio dormindo",
    width: 2880,
    height: 4032,
    className: "rounded",
  },
  {
    src: "/images/about/me_running.jpeg",
    alt: "Eu correndo",
    width: 2662,
    height: 3727,
    className: "rounded",
  },
  {
    src: "/images/about/me_jiujitsu.jpeg",
    alt: "Eu no jiu jitsu",
    width: 2340,
    height: 3276,
    className: "rounded -mt-4",
  },
  {
    src: "/images/about/me_chating.jpeg",
    alt: "Eu conversando",
    width: 732,
    height: 1024,
    className: "rounded",
  },
  {
    src: "/images/about/me_claudio_coffee.jpeg",
    alt: "Eu com Claudio e um café",
    width: 2206,
    height: 3088,
    className: "rounded -mt-4",
  },
  {
    src: "/images/about/me_playing_piano.jpeg",
    alt: "Eu tocando teclado",
    width: 732,
    height: 1024,
    className: "rounded",
  },
];
