export const SITE_URL = "https://ffzanini.dev" as const;

export const PERSON = {
  name: "Felipe Frantz Zanini",
  nameShort: "Felipe Frantz",
  nickname: "ffzanini",
  jobTitle: "Senior Software Engineer & Frontend Architect",
  jobTitleEn: "Senior Software Engineer & Frontend Architect",
  description:
    "Felipe Frantz Zanini (ffzanini) - Senior Software Engineer & Frontend Architect especializado em desenvolvimento web, frontend e fullstack. Desenvolvedor React, Next.js e TypeScript. Escritor, desenvolvedor de jogos indie e faixa marrom de Jiu Jitsu. Portfolio com projetos, stack tecnológica e contato. Pelotas, Brasil.",
  descriptionLong:
    "Felipe Frantz Zanini (ffzanini) - Senior Software Engineer & Frontend Architect com foco em desenvolvimento web, frontend e fullstack. Especialista em React, Next.js, TypeScript e tecnologias modernas. Desenvolvedor de software, escritor, desenvolvedor de jogos indie e faixa marrom de Jiu Jitsu. Portfolio pessoal com projetos desenvolvidos, stack tecnológica completa e formulário de contato. Localizado em Pelotas, Rio Grande do Sul, Brasil.",
} as const;

export const SEO_KEYWORDS = [
  // Nome e variações
  "Felipe Frantz Zanini",
  "Felipe Frantz",
  "Felipe Zanini",
  "Felipe",
  "ffzanini",
  "ffzanini.dev",

  // Profissão e títulos
  "software engineer",
  "engenheiro de software",
  "senior software engineer",
  "engenheiro de software sênior",
  "frontend architect",
  "arquiteto de frontend",
  "arquiteto frontend",
  "desenvolvedor de software",
  "software developer",
  "desenvolvedor",
  "developer",
  "programador",
  "programmer",
  "desenvolvedor web",
  "web developer",
  "desenvolvedor frontend",
  "frontend developer",
  "desenvolvedor fullstack",
  "fullstack developer",
  "full stack developer",

  // Tecnologias e habilidades
  "React",
  "React.js",
  "Next.js",
  "NextJS",
  "TypeScript",
  "JavaScript",
  "Node.js",
  "NodeJS",
  "Tailwind CSS",
  "TailwindCSS",
  "CSS3",
  "HTML5",
  "frontend",
  "front-end",
  "fullstack",
  "full-stack",
  "back-end",
  "backend",

  // Áreas de atuação
  "desenvolvimento",
  "development",
  "desenvolvimento web",
  "web development",
  "desenvolvimento de software",
  "software development",
  "desenvolvimento frontend",
  "frontend development",
  "desenvolvimento fullstack",
  "fullstack development",
  "programação",
  "programming",
  "codificação",
  "coding",

  // Portfolio e projetos
  "portfolio",
  "portfólio",
  "portfólio pessoal",
  "personal portfolio",
  "portfólio profissional",
  "professional portfolio",
  "projetos",
  "projects",
  "portfólio de desenvolvedor",
  "developer portfolio",

  // Localização
  "Pelotas",
  "Rio Grande do Sul",
  "RS",
  "Brasil",
  "Brazil",
  "desenvolvedor Pelotas",
  "developer Pelotas",
  "software engineer Pelotas",

  // Outros termos relevantes
  "consultoria",
  "consulting",
  "freelancer",
  "freelance",
  "contratação",
  "hire",
  "contratar desenvolvedor",
  "hire developer",
  "escritor",
  "writer",
  "screenwriter",
  "roteirista",
  "game developer",
  "desenvolvedor de jogos",
  "indie games",
  "jogos indie",
  "Jiu Jitsu",
  "BJJ",
] as const;

export const DEFAULT_OG_IMAGE = {
  url: "/images/visit-card.png",
  width: 1120,
  height: 630,
  alt: "Felipe Frantz Zanini | Senior Software Engineer & Frontend Architect | ffzanini.dev",
} as const;
