import {
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiMui,
  SiBootstrap,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiVite,
  SiNextdotjs,
  SiVuedotjs,
  SiVuetify,
  SiPhp,
  SiLaravel,
  SiCodeigniter,
  SiRuby,
  SiRubyonrails,
  SiGodotengine,
  SiAseprite,
  SiAudacity,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiFirebase,
  SiCloudflare,
  SiStorybook,
  SiObsstudio,
  SiVercel,
  SiDocker,
  SiGithub,
  SiGit,
  SiGitlab,
} from "react-icons/si";

import { LuPalette, LuServer, LuCloud } from "react-icons/lu";

export const categories = [
  {
    icon: LuPalette,
    title: "Frontend",
    sub_title: "frontend",
    technologies: [
      { name: "React", icon: SiReact, featured: true, color: "#61DAFB" },
      {
        name: "TypeScript",
        icon: SiTypescript,
        featured: true,
        color: "#3178C6",
      },
      {
        name: "JavaScript",
        icon: SiJavascript,
        featured: true,
        color: "#F7DF1E",
      },
      { name: "Next.js", icon: SiNextdotjs, featured: true, color: "#000000" },
      { name: "Vue.js", icon: SiVuedotjs, featured: false, color: "#4FC08D" },
      { name: "Vite", icon: SiVite, featured: true, color: "#646CFF" },
      { name: "HTML5", icon: SiHtml5, featured: true, color: "#E34F26" },
      { name: "CSS3", icon: SiCss3, featured: true, color: "#1572B6" },
      {
        name: "Tailwind",
        icon: SiTailwindcss,
        featured: true,
        color: "#06B6D4",
      },
      { name: "MUI", icon: SiMui, featured: false, color: "#007FFF" },
      {
        name: "Bootstrap",
        icon: SiBootstrap,
        featured: false,
        color: "#7952B3",
      },
      { name: "Vuetify", icon: SiVuetify, featured: false, color: "#1867C0" },
      {
        name: "Storybook",
        icon: SiStorybook,
        featured: false,
        color: "#FF4785",
      },
    ],
    bgColor: "from-gray-100 to-gray-300 dark:from-gray-700 dark:to-gray-800",
    borderColor: "border-gray-400/50 dark:border-gray-900/50",
  },
  {
    icon: LuServer,
    title: "Backend",
    sub_title: "backend",
    technologies: [
      { name: "Node.js", icon: SiNodedotjs, featured: true, color: "#339933" },
      { name: "Express", icon: SiExpress, featured: true, color: "#000000" },
      { name: "NestJS", icon: SiNestjs, featured: false, color: "#E0234E" },
      { name: "PHP", icon: SiPhp, featured: true, color: "#777BB4" },
      { name: "Laravel", icon: SiLaravel, featured: false, color: "#FF2D20" },
      {
        name: "CodeIgniter",
        icon: SiCodeigniter,
        featured: true,
        color: "#EF4223",
      },
      { name: "Ruby", icon: SiRuby, featured: false, color: "#CC342D" },
      {
        name: "Rails",
        icon: SiRubyonrails,
        featured: false,
        color: "#CC0000",
      },
      {
        name: "PostgreSQL",
        icon: SiPostgresql,
        featured: false,
        color: "#336791",
      },
      { name: "MySQL", icon: SiMysql, featured: true, color: "#4479A1" },
      { name: "MongoDB", icon: SiMongodb, featured: false, color: "#47A248" },
      { name: "Firebase", icon: SiFirebase, featured: false, color: "#FFCA28" },
    ],
    bgColor: "from-gray-100 to-gray-300 dark:from-gray-700 dark:to-gray-800",
    borderColor: "border-gray-400/50 dark:border-gray-900/50",
  },

  {
    icon: LuCloud,
    title: "DevOps & Gaming",
    sub_title: "devops",
    technologies: [
      { name: "Vercel", icon: SiVercel, featured: true, color: "#000000" },
      { name: "Docker", icon: SiDocker, featured: false, color: "#2496ED" },
      {
        name: "Cloudflare",
        icon: SiCloudflare,
        featured: false,
        color: "#F38020",
      },
      { name: "GitHub", icon: SiGithub, featured: true, color: "#181717" },
      { name: "Git", icon: SiGit, featured: true, color: "#F05032" },
      { name: "GitLab", icon: SiGitlab, featured: true, color: "#FC6D26" },
      {
        name: "Godot",
        icon: SiGodotengine,
        featured: true,
        color: "#478CBF",
      },
      { name: "Aseprite", icon: SiAseprite, featured: true, color: "#7D929E" },
      { name: "Audacity", icon: SiAudacity, featured: false, color: "#0000CC" },
      {
        name: "OBS Studio",
        icon: SiObsstudio,
        featured: false,
        color: "#000000",
      },
    ],
    bgColor: "from-gray-100 to-gray-300 dark:from-gray-700 dark:to-gray-800",
    borderColor: "border-gray-400/50 dark:border-gray-900/50",
  },
];

export const mainTechStack = [
  {
    name: "React",
    icon: SiReact,
    bgColor: "bg-cyan-500/10 dark:bg-cyan-500/20",
    iconColor: "text-cyan-500",
    borderColor: "border-cyan-200 dark:border-cyan-800",
  },
  {
    name: "Next.js",
    icon: SiNextdotjs,
    bgColor: "bg-slate-500/10 dark:bg-slate-500/20",
    iconColor: "text-slate-700 dark:text-slate-300",
    borderColor: "border-slate-200 dark:border-slate-700",
  },
  {
    name: "PHP",
    icon: SiPhp,
    bgColor: "bg-indigo-500/10 dark:bg-indigo-500/20",
    iconColor: "text-indigo-600 dark:text-indigo-400",
    borderColor: "border-indigo-200 dark:border-indigo-800",
  },
  {
    name: "TypeScript",
    icon: SiTypescript,
    bgColor: "bg-blue-500/10 dark:bg-blue-500/20",
    iconColor: "text-blue-600 dark:text-blue-400",
    borderColor: "border-blue-200 dark:border-blue-800",
  },
];
